In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
customers = pd.read_csv('crimestat (1).csv')
customers.head

/var/folders/9n/qnh7vnj50mb9p3j36q9cp78h0000gn/T/ipykernel_17095/2638251669.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  customers = pd.read_csv('crimestat (1).csv')

<bound method NDFrame.head of                INC NUMBER    OCCURRED ON    OCCURRED TO   UCR CRIME CATEGORY  \
0               2.016E+14   11/1/15 0:00    1/9/16 0:00  MOTOR VEHICLE THEFT
1               2.016E+14   11/1/15 0:00            NaN                 RAPE
2               2.015E+14   11/1/15 0:00   11/1/15 9:00        LARCENY-THEFT
3               2.015E+14   11/1/15 0:00   11/1/15 5:00  MOTOR VEHICLE THEFT
4               2.015E+14   11/1/15 0:00  11/1/15 11:50  MOTOR VEHICLE THEFT
...                   ...            ...            ...                  ...
131671  201700000000000.0  11/17/17 4:00  11/17/17 4:06             BURGLARY
131672  201700000000000.0  11/17/17 4:15  11/17/17 4:30        LARCENY-THEFT
131673  201700000000000.0  11/17/17 5:00  11/17/17 9:50  MOTOR VEHICLE THEFT
131674  201700000000000.0  11/17/17 5:34            NaN   AGGRAVATED ASSAULT
131675  201700000000000.0  11/17/17 5:50  11/17/17 7:50             BURGLARY

                  100 BLOCK ADDR      ZIP                   PREMISE TYPE
0       N 43RD AVE & W CACTUS RD  85029.0            SINGLE FAMILY HOUSE
1              13XX E ALMERIA RD  85006.0            SINGLE FAMILY HOUSE
2                 51XX N 15TH ST  85014.0                      APARTMENT
3            102XX W MEDLOCK AVE  85307.0            SINGLE FAMILY HOUSE
4                 69XX W WOOD ST  85043.0            SINGLE FAMILY HOUSE
...                          ...      ...                            ...
131671        22XX E BROADWAY RD  85040.0    DEPARTMENT / DISCOUNT STORE
131672   16XX E INDIAN SCHOOL RD  85016.0     CONVENIENCE MARKET / STORE
131673          43XX N 103RD AVE  85037.0                      APARTMENT
131674            8XX N 59TH AVE  85043.0  ABANDONED/CONDEMNED STRUCTURE
131675            51XX N 39TH DR  85019.0            SINGLE FAMILY HOUSE

[131676 rows x 7 columns]>

In [5]:
customers.sort_index(inplace=True)
customers.head()

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
0,2.016E+14,11/1/15 0:00,1/9/16 0:00,MOTOR VEHICLE THEFT,N 43RD AVE & W CACTUS RD,85029.0,SINGLE FAMILY HOUSE
1,2.016E+14,11/1/15 0:00,NaN,RAPE,13XX E ALMERIA RD,85006.0,SINGLE FAMILY HOUSE
2,2.015E+14,11/1/15 0:00,11/1/15 9:00,LARCENY-THEFT,51XX N 15TH ST,85014.0,APARTMENT
3,2.015E+14,11/1/15 0:00,11/1/15 5:00,MOTOR VEHICLE THEFT,102XX W MEDLOCK AVE,85307.0,SINGLE FAMILY HOUSE
4,2.015E+14,11/1/15 0:00,11/1/15 11:50,MOTOR VEHICLE THEFT,69XX W WOOD ST,85043.0,SINGLE FAMILY HOUSE

In [6]:
zip = customers.ZIP
zip

0         85029.0
1         85006.0
2         85014.0
3         85307.0
4         85043.0
           ...
131671    85040.0
131672    85016.0
131673    85037.0
131674    85043.0
131675    85019.0
Name: ZIP, Length: 131676, dtype: float64

In [8]:
zip_area1 = customers[(customers.ZIP<85099)] # group crimes by zip codes
zip_area1

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
0,2.016E+14,11/1/15 0:00,1/9/16 0:00,MOTOR VEHICLE THEFT,N 43RD AVE & W CACTUS RD,85029.0,SINGLE FAMILY HOUSE
1,2.016E+14,11/1/15 0:00,NaN,RAPE,13XX E ALMERIA RD,85006.0,SINGLE FAMILY HOUSE
2,2.015E+14,11/1/15 0:00,11/1/15 9:00,LARCENY-THEFT,51XX N 15TH ST,85014.0,APARTMENT
4,2.015E+14,11/1/15 0:00,11/1/15 11:50,MOTOR VEHICLE THEFT,69XX W WOOD ST,85043.0,SINGLE FAMILY HOUSE
5,2.016E+14,11/1/15 0:00,3/22/16 0:36,LARCENY-THEFT,33XX W CAMELBACK RD,85017.0,PARKING LOT
...,...,...,...,...,...,...,...
131671,201700000000000.0,11/17/17 4:00,11/17/17 4:06,BURGLARY,22XX E BROADWAY RD,85040.0,DEPARTMENT / DISCOUNT STORE
131672,201700000000000.0,11/17/17 4:15,11/17/17 4:30,LARCENY-THEFT,16XX E INDIAN SCHOOL RD,85016.0,CONVENIENCE MARKET / STORE
131673,201700000000000.0,11/17/17 5:00,11/17/17 9:50,MOTOR VEHICLE THEFT,43XX N 103RD AVE,85037.0,APARTMENT
131674,201700000000000.0,11/17/17 5:34,NaN,AGGRAVATED ASSAULT,8XX N 59TH AVE,85043.0,ABANDONED/CONDEMNED STRUCTURE
131675,201700000000000.0,11/17/17 5:50,11/17/17 7:50,BURGLARY,51XX N 39TH DR,85019.0,SINGLE FAMILY HOUSE

In [10]:
zip_area2 = customers[(customers.ZIP <85199)& (customers.ZIP > 85099)] # group crimes by zip codes
zip_area2

Empty DataFrame
Columns: [INC NUMBER, OCCURRED ON, OCCURRED TO, UCR CRIME CATEGORY, 100 BLOCK ADDR, ZIP, PREMISE TYPE]
Index: []

In [11]:
zip_area3 = customers[(customers.ZIP <85299)& (customers.ZIP > 85199)] # group crimes by zip codes
zip_area3

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
19,2.016E+14,11/1/15 0:01,1/7/16 12:00,MOTOR VEHICLE THEFT,48XX E DESERT COVE AVE,85254.0,CONDO / TOWNHOUSE
65,2.015E+14,11/1/15 10:08,11/1/15 10:08,LARCENY-THEFT,168XX N TATUM BLVD,85254.0,RETAIL BUSINESS
67,2.015E+14,11/1/15 11:35,NaN,LARCENY-THEFT,136XX N SCOTTSDALE RD,85254.0,RETAIL BUSINESS
156,2.015E+14,11/1/15 22:45,11/2/15 7:30,LARCENY-THEFT,56XX E GELDING DR,85254.0,SINGLE FAMILY HOUSE
248,2.015E+14,11/2/15 14:37,11/2/15 14:38,LARCENY-THEFT,48XX E CACTUS RD,85254.0,CHILD CARE / DAY CARE
...,...,...,...,...,...,...,...
131543,201700000000000.0,11/16/17 14:00,11/18/17 12:23,BURGLARY,50XX E REDFIELD RD,85254.0,SINGLE FAMILY HOUSE
131638,201700000000000.0,11/16/17 23:00,11/17/17 8:00,LARCENY-THEFT,62XX E WINCHCOMB DR,85254.0,VEHICLE
131639,201780000000.0,11/16/17 23:00,11/17/17 6:00,LARCENY-THEFT,63XX E CAROLINA DR,85254.0,DRIVEWAY
131654,201780000000.0,11/17/17 0:00,11/17/17 6:30,LARCENY-THEFT,142XX N 62ND ST,85254.0,SINGLE FAMILY HOUSING
131669,201700000000000.0,11/17/17 3:17,NaN,LARCENY-THEFT,59XX E SHEENA DR,85254.0,CARPORT

In [12]:
zip_area4 = customers[(customers.ZIP <85399)& (customers.ZIP > 85299)] # group crimes by zip codes
zip_area4

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
3,2.015E+14,11/1/15 0:00,11/1/15 5:00,MOTOR VEHICLE THEFT,102XX W MEDLOCK AVE,85307.0,SINGLE FAMILY HOUSE
13,2.016E+14,11/1/15 0:01,3/28/16 17:20,LARCENY-THEFT,46XX W FREMONT RD,85339.0,SINGLE FAMILY HOUSE
33,2.015E+14,11/1/15 2:00,11/1/15 14:20,MOTOR VEHICLE THEFT,85XX W MIAMI ST,85353.0,STREET / ROADWAY / ALLEY / SIDEWALK
42,2.015E+14,11/1/15 5:38,11/1/15 9:35,MOTOR VEHICLE THEFT,87XX S 47TH LN,85339.0,STREET / ROADWAY / ALLEY / SIDEWALK
58,2.0158E+11,11/1/15 9:14,11/27/15 9:15,BURGLARY,47XX W HARWELL RD,85339.0,SINGLE FAMILY HOUSING
...,...,...,...,...,...,...,...
131522,201880000000.0,11/16/17 10:45,11/16/17 11:30,LARCENY-THEFT,77XX S 53RD DR,85339.0,SINGLE FAMILY HOUSE
131565,201700000000000.0,11/16/17 15:50,NaN,LARCENY-THEFT,49XX W BELL RD,85306.0,CONVENIENCE MARKET / STORE
131566,201700000000000.0,11/16/17 16:00,11/16/17 16:06,LARCENY-THEFT,50XX W CACTUS RD,85304.0,GROCERY / SUPER MARKET
131573,201700000000000.0,11/16/17 16:40,11/16/17 16:41,LARCENY-THEFT,50XX W CACTUS RD,85304.0,GROCERY / SUPER MARKET
131584,201700000000000.0,11/16/17 17:45,11/16/17 21:00,BURGLARY,71XX W PARK ST,85339.0,SINGLE FAMILY HOUSE

In [19]:
n.sort_values(by=['UCR CRIME CATEGORY', 'PREMISE TYPE'],ascending=[True,False])

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
7443,2.015E+14,12/16/15 2:41,NaN,AGGRAVATED ASSAULT,16XX E MADISON ST,85034.0,WAREHOUSE / FACTORY
27874,2.016E+14,4/15/16 0:19,NaN,AGGRAVATED ASSAULT,71XX S 51ST AVE,85339.0,WAREHOUSE / FACTORY
37638,2.016E+14,6/10/16 17:15,6/13/16 9:20,AGGRAVATED ASSAULT,15XX S 47TH AVE,85043.0,WAREHOUSE / FACTORY
38975,2.016E+14,6/18/16 9:53,6/18/16 9:53,AGGRAVATED ASSAULT,15XX W CAMELBACK RD,85013.0,WAREHOUSE / FACTORY
96237,2.017E+14,5/8/17 10:00,NaN,AGGRAVATED ASSAULT,214XX N 15TH LN,85027.0,WAREHOUSE / FACTORY
...,...,...,...,...,...,...,...
79880,2.017E+14,2/4/17 20:15,2/4/17 20:19,ROBBERY,36XX W THOMAS RD,85009.0,NaN
101393,2.017E+14,6/4/17 21:40,NaN,ROBBERY,N 36TH AVE & W EVA ST,85051.0,NaN
114647,2.017E+14,8/16/17 3:43,8/16/17 3:43,ROBBERY,N 7TH AVE & W COLTER ST,85013.0,NaN
126844,2.017E+14,10/21/17 21:45,NaN,ROBBERY,95XX W MONTE VISTA RD,85037.0,NaN
131436,201700000000000.0,11/15/17 20:00,NaN,ROBBERY,18XX W CAMELBACK RD,85015.0,NaN

In [17]:
npub = n.groupby(['UCR CRIME CATEGORY'])
type(npub)

pandas.core.groupby.generic.DataFrameGroupBy

In [25]:
npub.get_group('AGGRAVATED ASSAULT')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
30,2.0151E+14,11/1/15 2:00,11/1/15 6:00,AGGRAVATED ASSAULT,50XX E THOMAS RD,85018.0,RESTAURANT
32,2.015E+14,11/1/15 2:00,11/1/15 12:00,AGGRAVATED ASSAULT,41XX N 51ST AVE,85031.0,RESTAURANT
45,2.015E+14,11/1/15 6:10,11/1/15 6:22,AGGRAVATED ASSAULT,42XX N 12TH ST,85014.0,PARKING LOT
79,2.015E+14,11/1/15 12:02,11/1/15 12:02,AGGRAVATED ASSAULT,69XX E CHAUNCEY LN,85054.0,APARTMENT
82,2.015E+14,11/1/15 13:00,11/1/15 13:30,AGGRAVATED ASSAULT,36XX W GARFIELD ST,85009.0,STREET / ROADWAY / ALLEY / SIDEWALK
...,...,...,...,...,...,...,...
131623,201700000000000.0,11/16/17 21:10,11/16/17 21:10,AGGRAVATED ASSAULT,37XX W LEWIS AVE,85009.0,STREET / ROADWAY / ALLEY / SIDEWALK
131646,201700000000000.0,11/16/17 23:50,11/16/17 23:57,AGGRAVATED ASSAULT,11XX E BUCKEYE RD,85034.0,STREET / ROADWAY / ALLEY / SIDEWALK
131651,201700000000000.0,11/17/17 0:00,11/17/17 0:00,AGGRAVATED ASSAULT,N 19TH AVE & W VOGEL AVE,85021.0,STREET / ROADWAY / ALLEY / SIDEWALK
131667,201700000000000.0,11/17/17 3:00,11/17/17 3:20,AGGRAVATED ASSAULT,6XX E TOWNLEY AVE,85020.0,APARTMENT
131674,201700000000000.0,11/17/17 5:34,NaN,AGGRAVATED ASSAULT,8XX N 59TH AVE,85043.0,ABANDONED/CONDEMNED STRUCTURE

In [26]:
npub.get_group('BURGLARY')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
18,2.016E+14,11/1/15 0:01,1/30/16 23:59,BURGLARY,40XX E MCDOWELL RD,85008.0,STOREROOM/SHED (COMMERCIAL)
21,2.015E+14,11/1/15 0:01,12/6/15 9:45,BURGLARY,6XX W BEVERLY LN,85023.0,SINGLE FAMILY HOUSE
23,2.015E+14,11/1/15 0:01,11/1/15 3:55,BURGLARY,38XX W HOLLY ST,85009.0,SINGLE FAMILY HOUSE
34,2.015E+14,11/1/15 2:38,11/1/15 3:05,BURGLARY,9XX E INDIAN SCHOOL RD,85014.0,FAST FOOD STORE
40,2.015E+14,11/1/15 4:25,NaN,BURGLARY,22XX E BROADWAY RD,85040.0,RESTAURANT
...,...,...,...,...,...,...,...
131652,201700000000000.0,11/17/17 0:00,11/24/17 12:02,BURGLARY,192XX N 22ND LN,85027.0,SINGLE FAMILY HOUSE
131655,201700000000000.0,11/17/17 0:01,11/18/17 8:00,BURGLARY,12XX N 54TH AVE,85043.0,OFFICE / COMMERCIAL BUILDING
131666,201700000000000.0,11/17/17 2:48,11/17/17 2:48,BURGLARY,166XX N 29TH DR,85053.0,SINGLE FAMILY HOUSE
131671,201700000000000.0,11/17/17 4:00,11/17/17 4:06,BURGLARY,22XX E BROADWAY RD,85040.0,DEPARTMENT / DISCOUNT STORE
131675,201700000000000.0,11/17/17 5:50,11/17/17 7:50,BURGLARY,51XX N 39TH DR,85019.0,SINGLE FAMILY HOUSE

In [30]:
npub.get_group('ROBBERY')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
39,2.015E+14,11/1/15 4:14,NaN,ROBBERY,138XX S 44TH ST,85044.0,STREET / ROADWAY / ALLEY / SIDEWALK
89,2.015E+14,11/1/15 13:33,11/1/15 13:35,ROBBERY,60XX S CENTRAL AVE,85042.0,STREET / ROADWAY / ALLEY / SIDEWALK
123,2.015E+14,11/1/15 17:00,11/1/15 17:30,ROBBERY,350XX N NORTH VALLEY PKWY,85086.0,SPECIALTY STORE
149,2.015E+14,11/1/15 21:00,11/1/15 21:10,ROBBERY,24XX E VAN BUREN ST,85008.0,STREET / ROADWAY / ALLEY / SIDEWALK
152,2.015E+14,11/1/15 21:15,NaN,ROBBERY,N 47TH AVE & W GLENROSA AVE,85031.0,STREET / ROADWAY / ALLEY / SIDEWALK
...,...,...,...,...,...,...,...
131618,201700000000000.0,11/16/17 20:30,NaN,ROBBERY,212XX N CAVE CREEK RD,85024.0,RESTAURANT
131627,201700000000000.0,11/16/17 21:54,NaN,ROBBERY,27XX E THOMAS RD,85016.0,RESTAURANT
131634,201700000000000.0,11/16/17 22:30,NaN,ROBBERY,32XX E WASHINGTON ST,85034.0,LIGHT RAIL TRAIN
131647,201700000000000.0,11/16/17 23:50,11/16/17 23:50,ROBBERY,20XX E THUNDERBIRD RD,85022.0,RESTAURANT
131665,201700000000000.0,11/17/17 2:35,11/17/17 2:35,ROBBERY,N 91ST AVE & W PINCHOT AVE,85037.0,STREET / ROADWAY / ALLEY / SIDEWALK

In [31]:
npub.get_group('MOTOR VEHICLE THEFT')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
0,2.016E+14,11/1/15 0:00,1/9/16 0:00,MOTOR VEHICLE THEFT,N 43RD AVE & W CACTUS RD,85029.0,SINGLE FAMILY HOUSE
3,2.015E+14,11/1/15 0:00,11/1/15 5:00,MOTOR VEHICLE THEFT,102XX W MEDLOCK AVE,85307.0,SINGLE FAMILY HOUSE
4,2.015E+14,11/1/15 0:00,11/1/15 11:50,MOTOR VEHICLE THEFT,69XX W WOOD ST,85043.0,SINGLE FAMILY HOUSE
14,2.015E+14,11/1/15 0:01,11/30/15 0:00,MOTOR VEHICLE THEFT,17XX W DESERT COVE AVE,85029.0,PARKING LOT
19,2.016E+14,11/1/15 0:01,1/7/16 12:00,MOTOR VEHICLE THEFT,48XX E DESERT COVE AVE,85254.0,CONDO / TOWNHOUSE
...,...,...,...,...,...,...,...
131640,201700000000000.0,11/16/17 23:00,11/16/17 23:45,MOTOR VEHICLE THEFT,31XX E THOMAS RD,85008.0,PARKING LOT
131641,201700000000000.0,11/16/17 23:00,11/17/17 5:30,MOTOR VEHICLE THEFT,33XX W FRAKTUR RD,85041.0,SINGLE FAMILY HOUSE
131656,201700000000000.0,11/17/17 0:01,11/17/17 7:10,MOTOR VEHICLE THEFT,43XX N 72ND DR,85033.0,STREET / ROADWAY / ALLEY / SIDEWALK
131660,201700000000000.0,11/17/17 1:00,11/17/17 6:00,MOTOR VEHICLE THEFT,200XX N 23RD AVE,85027.0,APARTMENT
131673,201700000000000.0,11/17/17 5:00,11/17/17 9:50,MOTOR VEHICLE THEFT,43XX N 103RD AVE,85037.0,APARTMENT

In [32]:
npub.get_group('LARCENY-THEFT')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
2,2.015E+14,11/1/15 0:00,11/1/15 9:00,LARCENY-THEFT,51XX N 15TH ST,85014.0,APARTMENT
5,2.016E+14,11/1/15 0:00,3/22/16 0:36,LARCENY-THEFT,33XX W CAMELBACK RD,85017.0,PARKING LOT
6,2.017E+14,11/1/15 0:00,NaN,LARCENY-THEFT,279XX N 23RD LN,85085.0,SINGLE FAMILY HOUSE
8,2.015E+14,11/1/15 0:00,11/11/15 9:30,LARCENY-THEFT,14XX E HIGHLAND AVE,85014.0,PARKING LOT
10,2.016E+14,11/1/15 0:01,3/27/16 8:00,LARCENY-THEFT,202XX N 6TH DR,85027.0,SINGLE FAMILY HOUSE
...,...,...,...,...,...,...,...
131663,201700000000000.0,11/17/17 2:16,NaN,LARCENY-THEFT,72XX W VERDE LN,85033.0,VEHICLE
131664,201700000000000.0,11/17/17 2:35,11/17/17 2:45,LARCENY-THEFT,12XX W MADISON ST,85007.0,STREET / ROADWAY / ALLEY / SIDEWALK
131668,201780000000.0,11/17/17 3:13,11/17/17 3:20,LARCENY-THEFT,206XX N 31ST DR,85027.0,SINGLE FAMILY HOUSING
131669,201700000000000.0,11/17/17 3:17,NaN,LARCENY-THEFT,59XX E SHEENA DR,85254.0,CARPORT
131672,201700000000000.0,11/17/17 4:15,11/17/17 4:30,LARCENY-THEFT,16XX E INDIAN SCHOOL RD,85016.0,CONVENIENCE MARKET / STORE

In [33]:
npub.get_group('RAPE')

,INC NUMBER,OCCURRED ON,OCCURRED TO,UCR CRIME CATEGORY,100 BLOCK ADDR,ZIP,PREMISE TYPE
1,2.016E+14,11/1/15 0:00,NaN,RAPE,13XX E ALMERIA RD,85006.0,SINGLE FAMILY HOUSE
7,2.017E+14,11/1/15 0:00,3/31/16 0:00,RAPE,38XX W CAMELBACK RD,85019.0,HOSPITAL
37,2.015E+14,11/1/15 4:00,11/1/15 4:05,RAPE,76XX W WHITTON AVE,85033.0,SINGLE FAMILY HOUSE
56,2.015E+14,11/1/15 9:00,NaN,RAPE,42XX W MULBERRY DR,85019.0,SINGLE FAMILY HOUSE
63,2.016E+14,11/1/15 10:00,11/1/15 22:00,RAPE,68XX W INDIAN SCHOOL RD,85033.0,SINGLE FAMILY HOUSE
...,...,...,...,...,...,...,...
131291,201700000000000.0,11/14/17 23:30,11/14/17 23:53,RAPE,15XX W COCOPAH ST,85007.0,SINGLE FAMILY HOUSE
131294,201800000000000.0,11/15/17 0:00,1/18/18 0:00,RAPE,10XX W MADISON ST,85007.0,OFFICE / COMMERCIAL BUILDING
131353,201800000000000.0,11/15/17 12:00,11/15/17 18:00,RAPE,47XX E PRESERVE WAY,85331.0,SINGLE FAMILY HOUSE
131419,201700000000000.0,11/15/17 19:00,11/15/17 19:30,RAPE,24XX E VAN BUREN ST,85034.0,PARKING LOT
131445,201700000000000.0,11/15/17 21:00,NaN,RAPE,32XX E ROOSEVELT ST,85008.0,STREET / ROADWAY / ALLEY / SIDEWALK